### PR TITLE
Update ampycloud citation details

### PR DESCRIPTION
**Pull request by fpavogt**
**Description:**

Basic PR to update the citation info for the code, following the publication of the associated [journal article](https://doi.org/10.5194/amt-17-4891-2024).

**Error(s) fixed:**

**Checklists**:
- [ ] New code includes dedicated tests.
- [ ] New code has been linted.
- [x] New code follows the project's style.
- [x] New code is compatible with the 3-Clause BSD license.
- [ ] CHANGELOG has been updated.
- [ ] AUTHORS has been updated.
- [ ] Copyright years in module docstrings have been updated.

### CODE REVIEW

**Comment by fpavogt** [comment]
@regDaniel : fyi, this is my first time toying around with the `CITATIONS.cff` file ... I've done the best I could, but we should definitely make sure that the final result (when the PR is merged) looks good (and correct).

**Comment by regDaniel** [comment]
Thanks @fpavogt tbh, I'm slightly overwhelmed with how to review this.. 😄 Not sure if you were suggesting the same yesterday but my suggestion would be to create a release 2.1.0 (along with a PR that I'm going to open in the afternoon) and then check if the citation appears correctly on Zenodo. Ok?
Also, I will open an MR in the afternoon with a new feature and - more importantly here - a fix for the build pipeline. Maybe we can coordinate the merging such that the build pipeline is fixed before we merge this one here.

**Comment by fpavogt** [comment]
@regDaniel: I would not worry (too much) about the impact on Zenodo. The main impact of the CITATION file will be on the main page of the repo (right-hand side) where the info will be clearly and easily usable. There's certainly no rush to merge this PR ... but at the same time, there's also no need to wait for a new release. A simple merge will already tell us if the outcome is as we expect it to be (on the main repo page).

**Comment by regDaniel** [comment]
Then I would suggest to merge even though the pipeline fails so we can see the outcome. There is almost no risk of side effects for this MR.

**Review by regDaniel — APPROVED** [review]

**Pull request merged**
