### PR TITLE
AMAROC-818 fix versions

### PR DESCRIPTION
**Pull request by regDaniel**
**Description:**

Fixes numpy version to < 2.0 to avoid attribute errors raised due to backward incompatibilities. Should fix the weekly test pipeline.

**Error(s) fixed:**

Fixed https://meteoswiss.atlassian.net/browse/AMAROC-818

**Checklists**:
- [ ] New code includes dedicated tests.
- [ ] New code has been linted.
- [ ] New code follows the project's style.
- [ ] New code is compatible with the 3-Clause BSD license.
- [ ] CHANGELOG has been updated.
- [ ] AUTHORS has been updated.
- [ ] Copyright years in module docstrings have been updated.

### CODE REVIEW

**Comment by regDaniel** [comment]
@fpavogt I assigned you for review because you set up the actions pipeline. I can however also assign someone else if you prefer.

**Comment by fpavogt** [comment]
What about fixing the issues ? As far as I can tell, the only problems are link to the use of ```np.infty``` that should be replaced with ```np.inf```, and ```np.in1d``` by ```np.isin```. 

These modifications should be backward compatible ... What do you think ? Is there something deeper that we should be cautious about ?

**Comment by regDaniel** [comment]
Hi @fpavogt sorry, I should have mentioned: I opened a ticket for that already. Here I just went for the fastest solution (priorities) in order to make the weekly pipeline run again, but fixing the issues is already planned.

**Comment by regDaniel** [comment]
obsolete with #129

**Pull request closed without merging**
