### PR TITLE
Terminology correction: alt -> height

### PR DESCRIPTION
**Pull request by fpavogt**
**Description:**

This PR implements a series of cosmetic changes to use height instead of altitude throughout the code. This is to reflect the fact that ceilometer hits and MSA are/must be both specified in ft above aerodrome level. 

Although these changes are cosmetic, they *will* impact the end users, as **the naming convention for the input Pandas DataFrame has changed**, with the `alt` column now being `height`. 

No version changes is included in this PR, but one should definitely raise it before making a new release to reflect this backward-incompatibly evolution.

In addition, this PR includes two additional minor changes: 
- the default example dataset now is 900s long (instead of 1200s)
- the parameter reset function now allows to only reset a subset of parameters is required
- minor tweaks to `setup.py`, to take into account the fact that `setuptools` must be explicitly requested as an `extras` package for dev work as of Python 3.12

**Error(s) fixed:**

**Checklists**:
- [x] New code includes dedicated tests.
- [x] New code has been linted.
- [x] New code follows the project's style.
- [x] New code is compatible with the 3-Clause BSD license.
- [x] CHANGELOG has been updated.
- [ ] AUTHORS has been updated.
- [x] Copyright years in module docstrings have been updated.

### CODE REVIEW

**Comment by fpavogt** [comment]
Hey @regDaniel, 

Here is the PR as discussed. I'll let you decide whether you prefer to merge it right away into `develop`, into your own branch, or delay the merge until your NSC update has been implemented.  

As mentioned above, this PR is purely "cosmetic" and does not change the functionality of the code in anyway - however, it does break the user interface (the naming convention for the input Pandas DataFrame has changed). 

I figured you'd decide what version bump was appropriate directly in your NSC update ?

**Review by regDaniel — APPROVED** [review]
Thanks for this rather tedious work @fpavogt ! I have nothing to add and will rebase this into my branch once it's merged.

**Comment by regDaniel** [comment]
On second thought... It's probably easier to merge my PR first as it's more localized and then rebase this one. I'll take care of it.

**Comment by fpavogt** [comment]
Sounds good. Should we bump the code version in this PR then ? I'd suggest to bump it to 1.1.0 ?

**Comment by regDaniel** [comment]
Yes we should, but I wonder whether we'd even need a major upgrade to 2.0 as the changes are somewhat breaking.

**Pull request merged**
